# Generated by Django 3.0.3 on 2020-02-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_research_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='research_description',
            field=models.TextField(default='Tell others what is your research about...'),
        ),
    ]
